version: "3"
services:
  backend:
    image: "petland/backend:latest"
    hostname: "backend"
    build: ./backend
    ports:
      - "50051:50051"
  envoy:
    image: "petland/envoy:latest"
    build: ./envoy
    ports:
      - "8080:8080"
  frontend:
    image: "petland/frontend:latest"
    build: ./frontend
    ports:
      - "3000:3000"